src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $username;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Client::class)]
    private $clients;

    #[ORM\Column(type: 'string', length: 255)]
    private $Email;

    public function __construct()
    {
        $this->clients = new ArrayCollection();
        
        //Si a la création le role d'admin n'ets pas attribué alors le compte créé est un compte bailleur.
        if($this->getRoles() != ['ROLE_USER','ROLE_ADMIN']){
            $this->setRoles(['ROLE_USER','ROLE_BAILLEUR']);


        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, client>
     */
    public function getClients(): Collection
    {
        return $this->clients;
    }

    public function addClient(client $client): self
    {
        if (!$this->clients->contains($client)) {
            $this->clients[] = $client;
            $client->setUser($this);
        }

        return $this;
    }

    public function removeClient(client $client): self
    {
        if ($this->clients->removeElement($client)) {
            // set the owning side to null (unless already changed)
            if ($client->getUser() === $this) {
                $client->setUser(null);
            }
        }

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }
}

templates/index/clients.html.twig
{% extends 'base.html.twig' %}

{% block title %}Clients{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

{% if alerter is not null %}
<div class='alert alert-danger'>
<p>Les contrats suivant doivent etre payé aujourd'hui:</p>
    <ul class='w3-ul' style="width:30%">
  
    
    {% for contrat in alerter %}
        <li> Contrat: {{ contrat.id }} du client :{{ contrat.client.nom }} {{ contrat.client.prenom }}</li>
    {% endfor %}
    
    </ul>
</div>    
{% else %}
  

{% endif %}





<h1>Liste des clients</h1>

<table class="table border-info">
<tr>
  <th>Nom</th>
  <th>Prenom</th>
  <th>Email</th>
  <th>Telephone</th>
  <td></td>
  <td></td>
  <td></td>
   

</tr>
{% if is_granted ('ROLE_ADMIN') %}
{% for client in clients %}




<tr>
  <td>{{client.nom}}</td>
  <td>{{client.prenom}}</td>
  <td>{{client.email}}</td>
  <td>{{client.telephone}}</td>
  
  <td><a href="{{path('client_delete_admin',{'clientId':client.id})}}" role="button" onclick="return confirm('etes vous sur de vouloir supprimer ce client?')" class=" btn btn-outline-danger">supprimer</a></td>
  <td><a href="{{path('client_update_admin',{'clientId':client.id})}}" role="button" class="btn btn-outline-info">modifier</a></td>
   <td><a href="{{path('admin_backoffice',{'clientId':client.id})}}" role="button" class="btn btn-outline-success">contrats</a></td>

</tr>
{% endfor %}
{% endif %}

{% if is_granted ('ROLE_BAILLEUR') %}
{% for client in app.user.clients %}




<tr>
  <td>{{client.nom}}</td>
  <td>{{client.prenom}}</td>
  <td>{{client.email}}</td>
  <td>{{client.telephone}}</td>
  
   <td><a href="{{path('client_delete',{'clientId':client.id})}}" role="button" onclick="return confirm('etes vous sur de vouloir supprimer ce client?')" class=" btn btn-outline-danger">supprimer</a></td>
  <td><a href="{{path('client_update',{'clientId':client.id})}}" role="button" class="btn btn-outline-info">modifier</a></td>
   <td><a href="{{path('contrat_display',{'clientId':client.id})}}" role="button" class="btn btn-outline-success">contrats</a></td>

</tr>
{% endfor %}
{% endif %}


<tr>
  <td class="border-bottom-0"><a href="{{path('client_create')}}" role="button" class="btn btn-success text-light">Ajouter un client</a></td>
  {% if clients is not empty %}
  <td class="border-bottom-0"><a href="{{path('contrat_create')}}" role="button" class="btn btn-warning text-light">Ajouter un contrat</a></td>
  {% endif %}
  

</tr>
</table>
{% endblock %}

templates/index/contrats.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contrats
{% endblock %}

{% block javascripts %}
<script>   
function afficherContratsArchives(){
	var bouttonContratsArchives = document.getElementById("contratsArchives");
    if (bouttonContratsArchives.style.display == "none") {
    bouttonContratsArchives.style.display = "block";
    } else {
    bouttonContratsArchives.style.display = "none";
    }}
    
    afficherContratsArchives();
	</script>
{% endblock %}
{% block body %}
	
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}

		#contratsArchives {
			display: none;
		}
	</style>

	<h1>Liste des contrats de
		{{ client.nom }}
		{{ client.prenom }}
	</h1>
	<td>
		<a href="{{path('contrat_create_for_client',{'clientId':client.id})}}" role="button" class="btn btn-warning text-light">Ajouter un contrat</a>
	</td>
	{% for contrat in client.contrats %}
		{% if contrat.archivé == false %}

			<h2>contrat :{{contrat.id}}</h2>
			<table class="table border-info">
				<tr>
					<th>Surface</th>


					<th>Montant du loyer</th>
					<th>Montant restant à payer</th>
					<th>Date de la prochaine échéance</th>
					<td></td>
					<td></td>
					<td></td>
				</tr>


				<tr>
					<td>{{contrat.surface}}</td>

					<td>{{contrat.loyer}}</td>
					<td>{{contrat.MontantRestant}}</td>
					<td>{{contrat.ProchaineEcheance | date('d/m/y')}}</td>
					<td>
						<a href="{{path('contrat_delete',{'contratId':contrat.id,'clientId':contrat.client.id})}}" onclick="return confirm('etes vous sur de vouloir supprimer ce client?')" role="button" class="btn btn-outline-danger">supprimer</a>
					</td>
					<td>
						<a href="{{path('contrat_update',{'contratId':contrat.id})}}" role="button" class="btn btn-outline-info">modifier</a>
					</td>

					<td>
						<a href="{{path('payements_display',{'contratId':contrat.id})}}" role="button" class="btn btn-outline-success">payements</a>
					</td>
				</tr>

				<tr>
					<td class="border-bottom-0">
						<a href="{{path('contrat_archiver',{'contratId':contrat.id})}}" role="button" class="w3-btn w3-white w3-border w3-border-brown w3-round-xlarge">archiver</a>
					</td>
				</tr>

			</table>
		{% endif %}
	{% endfor %}
	{% for contrat in client.contrats %}
		{% if contrat.archivé == true %}
			{% if loop.index0 == 0 %}
				<button onclick="afficherContratsArchives()">Les contrats archivés</button>


				<div id="contratsArchives">
					<table>
						<tr>
							<th>Surface</th>


							<th>Montant du loyer</th>
							<th>Montant restant à payer</th>
							<th>Date de la prochaine échéance</th>
						</tr>
					{% endif %}
					<tr>
						<td>{{contrat.surface}}</td>

						<td>{{contrat.loyer}}</td>
						<td>{{contrat.MontantRestant}}</td>
						<td>{{contrat.ProchaineEcheance | date('d/m/y')}}</td>
					</tr>
				{% endif %}
			{% endfor %}
		</table>
	</div>
{% endblock %}

templates/index/dataform.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ formName }} - {{ parent() }}{% endblock %}

{% block body %}
  <!-- The Form Section -->
  <div class="w3-container w3-content w3-center w3-padding-64" style="max-width:800px" id="form">
      <h1>{{ formName }}</h1>
      <div>
        {{ form(dataForm) }}
      </div>
  </div>
{% endblock %}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenue sur Interloc ! {% endblock %}

{% block body %}
    <h1 class='titre'>Bienvenue sur Interloc !</h1>
    <p class='paragraphe'>Gérez vos bails en toute simplicité avec notre tout nouveau Gestionnaire de location !
    Les différentes étapes de vos contrats seront suivis par notre application.
    De leurs créations à leur archivage.
    N'hésitez pas à créer un compte dès maintenant <a class="btn btn-success text-light" href="{{path('app_register')}}" >en cliquant ici !</a>
    </p>
    <div class="d-flex flex-column flex-lg-row justify-content-center  w-100"id="etapes" >
        
        <figure class="figure ">
            <img src="{{asset('images/portrait.png ')}}" class= " figure-img border border-success rounded-circle border-3"  alt="etape-client">
            <figcaption class="figure-caption text-right rounded-5 border border-success rounded-pill  text-light p-3">Commencez par créer votre client ...</figcaption>
        </figure>
        <figure class="figure"> 
            <img src="{{asset('images/fleche.png')}}"class=" figure-img"  alt="fleche">
            

        </figure>
        <figure class="figure">
            <img src="{{asset('images/contracter.png')}}"class=" figure-img border border-success rounded-circle border-3"  alt="etape-contrat">
            <figcaption class="figure-caption text-right rounded-5 border border-success rounded-pill  text-light p-3">Puis liez lui un contrat ...</figcaption>       
        </figure>
         <figure class="figure">
            <img src="{{asset('images/fleche.png')}}"class=" figure-img"  alt="fleche">
            
         </figure>
        <figure class="figure">
            <img src="{{asset('images/paiement.png')}}"class=" figure-img border border-success rounded-circle border-3"  alt="etape-paiement">
            <figcaption class="figure-caption text-right rounded-5 border border-success rounded-pill text-light p-3">Il ne vous reste plus qu'a gérer les paiements qui lui seront liés !</figcaption>
        </figure>
        

    </div>
    <br></br>
    <div></div>

    



{% endblock %}

templates/index/mentionsLegales.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenue sur Interloc ! {% endblock %}

{% block body %}
        <h1>Mentions légales</h1>

En vigueur au 21/07/2022
<p>Conformément aux dispositions des Articles 6-III et 19 de la Loi n°2004-575 du 21 juin 2004 pour la
Confiance dans l’économie numérique, dite L.C.E.N., il est porté à la connaissance des utilisateurs et
visiteurs, ci-après l""Utilisateur", du site www.interloc.fr , ci-après le "Site", les présentes mentions
légales.
La connexion et la navigation sur le Site par l’Utilisateur implique acceptation intégrale et sans réserve
des présentes mentions légales.
Ces dernières sont accessibles sur le Site à la rubrique « Mentions légales ».</p>

<h2>ARTICLE 1 - L'EDITEUR</h2>
<p>L’édition et la direction de la publication du Site est assurée par Clergue Jordan, domiciliée 9 allée des
sablières, dont le numéro de téléphone est 0652525252, et l'adresse e-mail
jordan.clergue@gmail.com.
ci-après l'"Editeur".
</p>
<h2>ARTICLE 2 - L'HEBERGEUR</h2>
<p>L'hébergeur du Site est la société O2SWITCH, dont le siège social est situé au 224 BD GUSTAVE
FLAUBERT, 63000 CLERMONT-FERRAND , avec le numéro de téléphone : 0444446040 +
adresse mail de contact
</p>
<h2>ARTICLE 3 - ACCES AU SITE</h2>
<p>Le Site est accessible en tout endroit, 7j/7, 24h/24 sauf cas de force majeure, interruption
programmée ou non et pouvant découlant d’une nécessité de maintenance.
En cas de modification, interruption ou suspension du Site, l'Editeur ne saurait être tenu responsable.
</p>
<h2>ARTICLE 4 - COLLECTE DES DONNEES</h2>
<p>Le site est exempté de déclaration à la Commission Nationale Informatique et Libertés (CNIL) dans la
mesure où il ne collecte aucune donnée concernant les utilisateurs.
Toute utilisation, reproduction, diffusion, commercialisation, modification de toute ou partie du Site,
sans autorisation de l’Editeur est prohibée et pourra entraînée des actions et poursuites judiciaires
telles que notamment prévues par le Code de la propriété intellectuelle et le Code civil.
</p>




{% endblock %}

templates/index/payements.html.twig
{% extends 'base.html.twig' %}

{% block title %}Payements
{% endblock %}

{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}
	</style>

	{% if alerte is defined %}
		{{ alerte }}
	{% endif %}


	<a href="{{path('payement_create',{'contratId':contrat.id})}}" role="button" class="w3-btn w3-white w3-border w3-border-yellow w3-round-xlarge">Archiver un payement</a>


	

	<div class="w3-row w3-section">
		<div class="w3-col" style="width:50px">
		
		</div>
		<div class="w3-container w3-content w3-center w3-padding-64" style="max-width:800px" id="form">
			{% if contrat.MontantRestant > 0 %}
			<h2 class="alert alert-danger">Montant restant à payer  :{{contrat.MontantRestant}}	<i class="material-icons-outlined">
				euro_symbol
			</i></h2>
			{% elseif contrat.MontantRestant < 0 %}
			<h2 class="alert alert-warning">Montant à rembourser :{{contrat.MontantRestant}}	<i class="material-icons-outlined">
				euro_symbol
			</i></h2>
			{% else %}
			<h2 class="alert alert-success">Montant entièrement réglé pour l'échéance en cours !	</h2>

			{% endif %}
			<h2 class="w3-center">Entrer un nouveau règlement</h2>
			<div>
				{{ form(form) }}
				
			</div>
		</div>


		<br>


		<h1>Liste des payements de
			{{ contrat.client.nom }}
			{{ contrat.client.prenom }}
			pour le contrat:
			{{ contrat.id }}
		</h1>

		{% for payement in payements %}
			{% if payement is not null %}


				<h2>payement :{{payement.id}}</h2>
				<table class="w3-table w3-bordered w3-centered ">
					<tr>
						<th>
							{% if payement.TypePayement == 'Payement'%}
							Payement
							{% else %}
							Remboursement
							{% endif %}

						</th>


						<th>Moyen payement</th>
						<th>Date</th>
					</tr>


					<tr>
						<td>{{payement.SommePayee}}</td>

						<td>
							{{payement.MoyenPayement}}


						</td>
						<td>
							{{payement.date|date('d/m/Y')}}
						</td>

					</tr>
				</table>
			{% endif %}

		{% endfor %}

	{% endblock %}

templates/index/sommeForm.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ formName }} - {{ parent() }}{% endblock %}

{% block body %}
  <!-- The Form Section -->
  <div class="w3-container w3-content w3-center w3-padding-64" style="max-width:800px" id="form">
      <h1>{{ formName }}</h1>
      <div>
        {{ form_row(form.SommePayee) }}
      </div>
  </div>
{% endblock %}